/**
 * CHANGELOG.md, generated from what the org actually did.
 *
 * A normal changelog answers "what changed". When the changes are made by
 * agents, that is not enough — you also need to know WHO made each one and WHY
 * it was attempted, because those are the two facts you cannot recover from the
 * diff, and they are the ones you need when something turns out to be wrong.
 *
 * So every commit is attributed to the seat and model that produced it, and
 * every mission carries its provenance: you asked for it, the chief proposed
 * it, or it came out of a video briefing. When a change looks wrong six weeks
 * later, the entry tells you whether to distrust a model, a suggestion source,
 * or your own instruction.
 *
 * Derived, never hand-edited. Everything here already exists in the per-mission
 * state.json; this only reads it.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { codename } from "./theme.js";
import type { Handoff, MissionOrigin, MissionState } from "./types.js";

export interface ChangelogEntry {
	id: string;
	codename: string;
	date: string;
	goal: string;
	verdict: string;
	outcome: string;
	origin?: MissionOrigin;
	costUsd: number;
	milestones: number;
	seats: { orchestrator: string; worker: string; bugSpotter: string };
	commits: { sha: string; featureId: string; message: string; handoff?: Handoff; corrective: boolean }[];
	/** Issues raised during the mission and what happened to each. */
	issues: { summary: string; disposition?: string; addressedBy?: string }[];
}

const seat = (m?: { provider: string; modelId: string }): string => (m ? `${m.provider}/${m.modelId}` : "—");

/** Read every completed mission recorded under a repo's .missions/runs. */
export function collectEntries(repo: string): ChangelogEntry[] {
	const runsDir = join(repo, ".missions", "runs");
	if (!existsSync(runsDir)) return [];

	const entries: ChangelogEntry[] = [];
	for (const dir of readdirSync(runsDir)) {
		const statePath = join(runsDir, dir, "state.json");
		if (!existsSync(statePath)) continue;
		let s: MissionState;
		try {
			s = JSON.parse(readFileSync(statePath, "utf-8")) as MissionState;
		} catch {
			continue;
		}
		if (!s.commits?.length) continue; // nothing shipped, nothing to log

		const handoffs = s.handoffs ?? [];
		const corrections = new Set((s.features ?? []).filter((f) => f.origin === "correction").map((f) => f.id));

		entries.push({
			id: s.id,
			codename: codename(s.id),
			date: (s.startedAt ?? "").slice(0, 10),
			goal: s.goal,
			verdict: s.finalVerdict ?? s.status,
			outcome: s.outcome ?? (s.status === "failed" ? "failed" : "unknown"),
			origin: s.origin,
			costUsd: s.costUsd ?? 0,
			milestones: (s.milestones ?? []).length,
			seats: {
				orchestrator: seat(s.routing?.orchestrator),
				worker: seat(s.routing?.worker),
				bugSpotter: seat(s.routing?.bugSpotter),
			},
			commits: s.commits.map((c) => ({
				sha: c.sha,
				featureId: c.featureId,
				message: c.message,
				handoff: handoffs.find((h) => h.commitSha === c.sha) ?? handoffs.find((h) => h.featureId === c.featureId),
				corrective: corrections.has(c.featureId),
			})),
			issues: handoffs.flatMap((h) =>
				h.issues.map((i) => ({ summary: i.summary, disposition: i.disposition, addressedBy: i.addressedBy })),
			),
		});
	}

	return entries.sort((a, b) => (a.id < b.id ? 1 : -1));
}

function describeOrigin(o: MissionOrigin | undefined): string {
	if (!o) return "unrecorded";
	switch (o.kind) {
		case "human":
			return "asked for directly";
		case "chief":
			return "proposed by the chief";
		case "suggestion":
			return `suggestion${o.note ? ` — ${o.note}` : ""}`;
		case "briefing":
			return `video briefing${o.sourceUrl ? ` — ${o.sourceUrl}` : ""}`;
		default:
			return String(o.kind);
	}
}

const esc = (s: string): string => String(s ?? "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
const trim = (s: string, n: number): string => (s.length > n ? `${s.slice(0, n - 1)}…` : s);

export function renderChangelog(entries: ChangelogEntry[], repoLabel: string): string {
	const out: string[] = [];
	out.push(`# Changelog — ${repoLabel}`);
	out.push("");
	out.push("Generated by `missions changelog`. Every commit is attributed to the agent seat that produced it.");
	out.push("Do not hand-edit: this file is derived from each mission's `state.json`.");
	out.push("");

	if (!entries.length) {
		out.push("_No missions have shipped commits in this repo yet._");
		return `${out.join("\n")}\n`;
	}

	const totalCost = entries.reduce((n, e) => n + e.costUsd, 0);
	const totalCommits = entries.reduce((n, e) => n + e.commits.length, 0);
	out.push(`${entries.length} mission(s) · ${totalCommits} commit(s) · $${totalCost.toFixed(2)} total`);
	out.push("");

	for (const e of entries) {
		const flag = e.outcome === "clean" ? "clean" : e.outcome === "failed" ? "**failed**" : "**needs review**";
		out.push(`## ${e.date} · ${e.codename}`);
		out.push("");
		out.push(`**${esc(e.goal)}**`);
		out.push("");
		out.push(
			`${flag} · verdict \`${e.verdict}\` · ${e.milestones} milestone(s) · $${e.costUsd.toFixed(2)} · _${describeOrigin(e.origin)}_`,
		);
		out.push("");
		out.push("| commit | feature | agent | change |");
		out.push("|---|---|---|---|");
		for (const c of e.commits) {
			const what = c.handoff?.completed ? trim(esc(c.handoff.completed), 150) : esc(c.message);
			const kind = c.corrective ? `${c.featureId} _(correction)_` : c.featureId;
			const conf = c.handoff?.confidence && c.handoff.confidence !== "high" ? ` _(${c.handoff.confidence} confidence)_` : "";
			out.push(`| \`${c.sha.slice(0, 8)}\` | ${kind} | worker · \`${e.seats.worker}\`${conf} | ${what} |`);
		}
		out.push("");
		out.push(`Planned by \`${e.seats.orchestrator}\` · adversarially reviewed by \`${e.seats.bugSpotter}\``);

		if (e.issues.length) {
			out.push("");
			out.push("Issues raised:");
			for (const i of e.issues) {
				const fate = !i.disposition
					? "**unruled**"
					: i.disposition === "addressed"
						? `addressed → \`${i.addressedBy ?? "?"}\``
						: "deferred";
				out.push(`- ${esc(i.summary)} — ${fate}`);
			}
		}
		out.push("");
	}

	return `${out.join("\n")}\n`;
}

/** Write CHANGELOG.md at the repo root and return its path. */
export function generateChangelog(repo: string, repoLabel: string): { path: string; entries: number } {
	const entries = collectEntries(repo);
	const path = join(repo, "CHANGELOG.md");
	writeFileSync(path, renderChangelog(entries, repoLabel));
	return { path, entries: entries.length };
}
